### ISSUE TITLE
Wrong address and wrong name, 2 German locations

### ISSUE THREAD

**Issue by hattom** [flux-framework/locator-map#1]
There are 2 entries in Germany.
One has the wrong address, the other has a typo on the name.

I'm happy to open a PR to fix both, if I can assume that the .csv file may be modified (or is it auto-generated?)?

**Comment by vsoch** [comment]
It's automatically generated from a sheet, so we'd want to fix in both places!

**Comment by hattom** [comment]
(linking the PR https://github.com/flux-framework/locator-map/pull/2)

**Comment by vsoch** [comment]
Closed with #2 The sheet is also updated!
